#!/bin/sh
#PBS -N  sequentiel
#PBS -l walltime=00:15:00
#PBS -q second_queue
echo "Queue name: " $PBS_O_QUEUE
echo "Server Name: " $PBS_SERVER
echo "JobID: " $PBS_JOBID
echo "Working dir: " $PBS_O_WORKDIR
echo "The job name: " $PBS_JOBNAME
echo "PBS_NODEFILE: " $PBS_NODEFILE
echo "PBS_O_HOST: " $PBS_O_HOST
echo "PBS_ARRAYID: " $PBS_ARRAYID
echo "PBS_ENVIRONMENT :" $PBS_ENVIRONMENT
echo "PBS_O_HOME: " $PBS_O_HOME
sleep (7)
