#!/bin/sh
#PBS -N  sequentiel
#PBS -l walltime=00:15:00
#PBS -q second_queue
echo "Queue name: " $PBS_O_QUEUE 
echo "Server Name: " $PBS_SERVER $SLURM_JOB_NODELIST 
echo "JobID: " $PBS_JOBID $SLURM_JOB_ID
echo "Working dir: " $PBS_O_WORKDIR $SLURM_SUBMIT_DIR
echo "The job name: " $PBS_JOBNAME $SLURM_JOB_NAME
echo "PBS_NODEFILE: " $PBS_NODEFILE
echo "PBS_O_HOST: " $PBS_O_HOST $SLURM_JOB_NODELIST
echo "PBS_ARRAYID: " $PBS_ARRAYID
echo "PBS_ENVIRONMENT :" $PBS_ENVIRONMENT
echo "PBS_O_HOME: " $PBS_O_HOME
sleep 300
#/home/traore/TEST/fibo_calc2 43 



