#!/bin/sh
#nbjobsparam=15
#PBS -N  sequentiel
#PBS -l walltime=03:50:00
# PBS -q first_queue 
# PBS -a 1830
#SBATCH -J myFristJob
#SBATCH -o /home/traore/VishnuProject/vishnu/build/myJob-%J-%j-%8j-%j-%-1j%.out
#SBATCH -e /home/traore/VishnuProject/vishnu/build/myJob-%j-%2aj-%-%3J-%4j.err
#SBATCH -p firstPart
#SBATCH --comment="my first slurm job"
#SBATCH --share
echo "Queue name: " $PBS_O_QUEUE 
echo "Server Name: " $PBS_SERVER $SLURM_JOB_NODELIST 
echo "JobID: " $PBS_JOBID $SLURM_JOB_ID
echo "Working dir: " $PBS_O_WORKDIR $SLURM_SUBMIT_DIR
echo "The job name: " $PBS_JOBNAME $SLURM_JOB_NAME
echo "PBS_NODEFILE: " $PBS_NODEFILE
echo "PBS_O_HOST: " $PBS_O_HOST $SLURM_JOB_NODELIST
echo "PBS_ARRAYID: " $PBS_ARRAYID
echo "PBS_ENVIRONMENT :" $PBS_ENVIRONMENT
echo "PBS_O_HOME: " $PBS_O_HOME
sleep 300
#/home/traore/TEST/fibo_calc2 43 



