'\" t
.\"     Title: vishnu_list_auth_systems
.\"    Author:  SysFera SA <info@sysfera.com>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: March 2012
.\"    Manual: UMS Command reference
.\"    Source: VISHNU 1.3
.\"  Language: English
.\"
.TH "VISHNU_LIST_AUTH_SYS" "1" "March 2012" "VISHNU 1.3" "UMS Command reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vishnu_list_auth_systems \- lists VISHNU user\-authentification systems
.SH "SYNOPSIS"
.HP \w'\fBvishnu_list_auth_systems\fR\ 'u
\fBvishnu_list_auth_systems\fR [\fB\-h\fR] [\fB\-a\fR] [\fB\-f\fR] [\fB\-u\ \fR\fB\fIuserId\fR\fR] [\fB\-i\ \fR\fB\fIauthSystemId\fR\fR]
.SH "DESCRIPTION"
.PP
This command allows to display all user\-authentication systems\&. By default, the user\-authentication systems where the user has a local user\-authentication config are listed\&.
.SH "OPTIONS"
.PP
\fB\-h \fR\fB\fIhelp\fR\fR
.RS 4
help about the command\&.
.RE
.PP
\fB\-a \fR\fB\fIlistAllAuthSystems\fR\fR
.RS 4
is an option for listing all VISHNU user\-authentication systems\&.
.RE
.PP
\fB\-f \fR\fB\fIlistFullInfo\fR\fR
.RS 4
is an admin option for listing full VISHNU user\-authentication systems information such as all concerned only the administrator: authLogin, authPassword and userPasswordEncryption \&.
.RE
.PP
\fB\-u \fR\fB\fIuserId\fR\fR
.RS 4
is an admin option for listing all user\-authentication systems in which a specific user has local user\-authentication configs\&.
.RE
.PP
\fB\-i \fR\fB\fIauthSystemId\fR\fR
.RS 4
is an option for listing a specific user\-authentication system\&.
.RE
.SH "ENVIRONMENT"
.PP
\fBVISHNU_CONFIG_FILE\fR
.RS 4
Contains the path to the local configuration file for VISHNU\&.
.RE
.SH "DIAGNOSTICS"
.PP
The following diagnostics may be issued on stderr and the command will return the code provided within brackets:
.PP
"Vishnu not available (Service bus failure)" [1]
.RS 4
.RE
.PP
"Vishnu not available (Database error)" [2]
.RS 4
.RE
.PP
"Vishnu not available (Database connection)" [3]
.RS 4
.RE
.PP
"Vishnu not available (System)" [4]
.RS 4
.RE
.PP
"Internal Error: Undefined exception" [9]
.RS 4
.RE
.PP
"There is no open session in this terminal" [13]
.RS 4
.RE
.PP
"Missing parameters" [14]
.RS 4
.RE
.PP
"Vishnu initialization failed" [15]
.RS 4
.RE
.PP
"Undefined error" [16]
.RS 4
.RE
.PP
"The userId is unknown" [21]
.RS 4
.RE
.PP
"The user is not an administrator" [25]
.RS 4
.RE
.PP
"The session key is unrecognized" [28]
.RS 4
.RE
.PP
"The sessionKey is expired\&. The session is closed\&." [29]
.RS 4
.RE
.PP
"The type of the user\-authentication system is unknown" [47]
.RS 4
.RE
.SH "EXAMPLE"
.PP
To list all user\-authentication systems:
.PP
vishnu_list_auth_systems
.SH "AUTHOR"
.PP
\fB SysFera SA\fR <\&info@sysfera.com\&>
.RS 4
Developed the first version of these man pages as part of the VISHNU project.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2012 SysFera SA
.br
.PP
These manual pages are provided under the following conditions:
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
.RE
.PP
This software is governed by the CECILL licence under French law and abiding by the rules of distribution of free software. You can use, modify and/ or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
.PP
As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty and the software's author, the holder of the economic rights, and the successive licensors have only limited liability.
.PP
In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software's suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
.sp
