#!/bin/sh
#nbjobsparam=15
#PBS -N  sequentiel
# PBS -a 1830
# PBS -l  walltime=10:00:00
# PBS -q second_queue 
# PBS -q first_queue
#PBS -q firstPart
#PBS -l walltime=01:00:00
# PBS -l walltime=1::2
# PBS -l nodes=1:ppn=2, walltime=10:00:00
# PBS -l nodes=1 
# PBS -l mem=2500b
#PBS -l ncpus=2
# PBS -W group_list=traore
# un cas d'erreur
# PBS -la mem=500 

#sleep 1 
sleep 3600
ls /home/traore/VishnuProject/vishnu/TMS
#/home/traore/TEST/fibo_calc2 43 

qsdfer/papa


