#!/bin/sh
#nbjobsparam=15
#PBS -N  sequentiel
#PBS -l walltime=03:50:00
# PBS -q second_queue 
#PBS  -q firstPart
#PBS -a 1830
echo "Queue name: " $PBS_O_QUEUE
echo "Server Name: " $PBS_SERVER
echo "JobID: " $PBS_JOBID
echo "Working dir: " $PBS_O_WORKDIR
echo "The job name: " $PBS_JOBNAME
echo "PBS_NODEFILE: " $PBS_NODEFILE
echo "PBS_O_HOST: " $PBS_O_HOST
echo "PBS_ARRAYID: " $PBS_ARRAYID
echo "PBS_ENVIRONMENT :" $PBS_ENVIRONMENT
echo "PBS_O_HOME: " $PBS_O_HOME
sleep 60
/home/traore/TEST/fibo_calc2 43 



