<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="IMS_Data"
    nsURI="http://www.sysfera.com/IMS/Data">
  <eClassifiers xsi:type="ecore:EEnum" name="MetricType" instanceTypeName="MetricType">
    <eAnnotations source="Description">
      <details key="content" value="The metric type is the type of metric to use"/>
    </eAnnotations>
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="CPUUSE" value="1"/>
    <eLiterals name="DISKSPACE" value="2"/>
    <eLiterals name="FREEDISKSPACE" value="3"/>
    <eLiterals name="MEMORY" value="4"/>
    <eLiterals name="FREEMEMORY" value="5"/>
    <eLiterals name="CPUNBR" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric" instanceTypeName="Metric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MetricType">
      <eAnnotations source="Description">
        <details key="content" value="The type of the metric"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="Description">
        <details key="content" value="The value of the metric"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="Description">
        <details key="content" value="The timestamp the metric had the value"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RestartType" instanceTypeName="RestartType">
    <eAnnotations source="Description">
      <details key="source" value="The restart type is the element that is to be restarted"/>
    </eAnnotations>
    <eLiterals name="UNDEFINED"/>
    <eLiterals name="SED" value="1"/>
    <eLiterals name="AGENT" value="2"/>
    <eLiterals name="DAEMON" value="3"/>
    <eLiterals name="ALL" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LoadShedType" instanceTypeName="LoadShedType">
    <eAnnotations source="Description">
      <details key="content" value="The load shed type reprensents how to proceed the load shed"/>
    </eAnnotations>
    <eLiterals name="UNDEFINED" literal="SOFT"/>
    <eLiterals name="HARD" value="1"/>
    <eLiterals name="SOFT" value="2" literal="SOFT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListMetric" instanceTypeName="ListMetric">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" upperBound="-1"
        eType="#//Metric" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="The metrics of the list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListProcesses" instanceTypeName="ListProcesses">
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" upperBound="-1"
        eType="#//Processes" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="The processes of the list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemInfo" instanceTypeName="SystemInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="Description">
        <details key="content" value="Amount of RAM memory available on the machine (in Bytes)"/>
        <details key="shortOption" value="m"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diskSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="Description">
        <details key="content" value="Amount of disk space available on the machine (in Bytes)"/>
        <details key="shortOption" value="d"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Processes" instanceTypeName="Processes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="The value of the metric"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="exportOp" instanceTypeName="exportOp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exportType" eType="#//exportType"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="exportType" instanceTypeName="exportType">
    <eAnnotations source="Description">
      <details key="content" value="The export type is the format to export an history of commands"/>
    </eAnnotations>
    <eLiterals name="UNDEFINED" literal="UNDEFINED"/>
    <eLiterals name="SHELL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="metricHistOp" instanceTypeName="metricHistOp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="">
      <eAnnotations source="Description">
        <details key="content" value="The start time to get the history"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="">
      <eAnnotations source="Description">
        <details key="content" value="The end time to get the history"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" instanceTypeName="restartOp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dietConfFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="The path to the diet configuration file"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vishnuConf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="The path to the vishnu configuration file"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
