<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TMS_Data"
    nsURI="http://www.sysfera.com/emf/tms/data" nsPrefix="tms_data">
  <eClassifiers xsi:type="ecore:EClass" name="Job" instanceTypeName="Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the id of the session that contained the job submission command"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="submitMachineId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the id of the machine on which the job has been submitted."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="submitMachineName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the name of the machine on which the job has been submitted."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Represents the id to job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Represents the name assigned to the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the path to the file containing job characteristics."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the path to the job output results."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the path to the file containing errors occured during job's execution. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobPrio" eType="#//JobPriority"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job priority. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCpus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the number of cpu per node used by the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobWorkingDir" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Indicates the directory where the job has been launched."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//JobStatus"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="The current status of the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="submitDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Date and time when job was submitted (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Represents the execution end date of the job (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job owner."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobQueue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the name of the queue or class associated to the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wallClockLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the maximum wall-clock time during which the job can run (in seconds)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job owner group name."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the textual description of the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Represents the memory size limit of the job ((in MegaBytes)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbNodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the total number of nodes used by the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbNodesAndCpuPerNode" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the number of nodes and processors per node used by the job (in the format nbNodes:nbCpuPerNode)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="batchJobId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="Represents the batch job id (given by the underlying batch scheduler )."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputDir" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Indicates the directory where the job has been launched."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListJobs" instanceTypeName="ListJobs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbJobs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Represents the total number of jobs in the list."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbRunningJobs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Represents of  running jobs in the list."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbWaitingJobs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Represents the total number of waiting jobs in the list."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobs" upperBound="-1" eType="#//Job"
        containment="true">
      <eAnnotations source="Description">
        <details key="content" value="Is a list of  job information  (jobId, jobName, ...)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubmitOptions" instanceTypeName="SubmitOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Assigns a job name. The default is the path of job"/>
        <details key="shortOption" value="n"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Assigns the queue or class of the job"/>
        <details key="shortOption" value="q"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wallTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="The maximum wall-clock time during which the job can run (in seconds)"/>
        <details key="shortOption" value="t"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the memory size that the job requires (in MegaBytes)"/>
        <details key="shortOption" value="m"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="The number of cpu per node that the job requires"/>
        <details key="shortOption" value="P"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbNodesAndCpuPerNode" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="The number of nodes and processors per node (in the format nbNodes:nbCpuPerNode). For example if you want to use 4 nodes with 3 cpus for each node, you must specify these numbers by &quot;4:3&quot;"/>
        <details key="shortOption" value="N"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputPath" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Assigns the path and file for job output"/>
        <details key="shortOption" value="o"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorPath" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Assigns the path and file for job error"/>
        <details key="shortOption" value="e"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mailNotification" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Assigns the notification type of the job. Valid type values are BEGIN, END, ERROR, and ALL (any state change)"/>
        <details key="shortOption" value="M"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mailNotifyUser" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="The name of user to receive email notification of state changes as defined by the option mailNotification. The default value is the submitting user"/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="group" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Assigns a job group name."/>
        <details key="shortOption" value="g"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workingDir" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Assigns a job remote working dir"/>
        <details key="shortOption" value="D"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cpuTime" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Assigns a job cpu limit time (in seconds or in the format [[HH:]MM:]SS)"/>
        <details key="shortOption" value="T"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectQueueAutom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="Description">
        <details key="content" value="allows to select automatically a queue which has the number of nodes requested by the user"/>
        <details key="shortOption" value="Q"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="criterion" eType="#//LoadCriterion"
        containment="true">
      <eAnnotations source="Description">
        <details key="content" value="Represents the scheduling criterion to automatically submit a job"/>
        <details key="shortOption" value="L"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileParams" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Sets a list of local files as parameters for the script.  &#xA;These files will be  uploaded onto the server before computing the script. At the execution time,  each path can be accessed through an environment variable.&#xA;E.g. --fileParams &quot;PFILE1=/path/to/file1 PFILE2=/path/to/file2&quot; or -F &quot;PFILE1=/path/to/file1 PFILE2=/path/to/file2&quot;.&#xA;At the execution, the environment variable $PFILE1, for example, will point to the uploaded copy of the file /path/to/file1. &#xA;&#xA;The option --fileParam or -f allows to set each file individually.&#xA;&#xA;NOTE: The name of parameter as well as those of the corresponding environment are case-insensitive.&#xA;"/>
        <details key="shortOption" value="F"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textParams" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="shortOption" value="V"/>
        <details key="content" value="Sets a list of parameters for the script so at the execution, each of parameter can be used as an environment variable.&#xA;E.g. --textParams &quot;PARAM1=value1 PARAM2=value2&quot; or -F &quot;PARAM1=value1 PARAM2=value2&quot;, will set the environment variables named PARAM1 and PARAM2 with value1 and value2, respectively. &#xA;&#xA;The option --textParam or -v allows to set each file individually.&#xA;&#xA;NOTE: The name of parameter as well as those of the corresponding environment are case-insensitive."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wid" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="shortOption" value="w"/>
        <details key="content" value="Associates the job to a given work."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListJobsOptions" instanceTypeName="ListJobsOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobId" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="lists the job with the specified id"/>
        <details key="shortOption" value="i"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCpu" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="lists the jobs with the specified number of CPUs per node"/>
        <details key="shortOption" value="P"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromSubmitDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="lists the jobs submitted after the specified date (UNIX timestamp)"/>
        <details key="shortOption" value="d"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toSubmitDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="lists jobs submitted before the specified date (UNIX timestamp)"/>
        <details key="shortOption" value="D"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="lists the jobs submitted by the specified owner"/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//JobStatus"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="lists the jobs with the specified status"/>
        <details key="shortOption" value="s"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="#//JobPriority"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="lists the jobs with the specified priority"/>
        <details key="shortOption" value="p"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="the jobs with the specified queue name"/>
        <details key="shortOption" value="q"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="lists the jobs with the specified status (combination of multiple status). Its format contains  the first letter or the value (interger) of each chosen status. For exemple to list the cancelled and terminated jobs,  you use the format CT or 65"/>
        <details key="shortOption" value="S"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="batchJob" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="Description">
        <details key="content" value="allows to select all jobs submitted  through the underlying batch scheduler  (jobs submitted through vishnu and out of vishnu)"/>
        <details key="shortOption" value="b"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JobPriority" instanceTypeName="JobPriority">
    <eLiterals name="UNDEFINED" value="-1" literal="UNDEFINED"/>
    <eLiterals name="VERY_LOW" value="1"/>
    <eLiterals name="LOW" value="2"/>
    <eLiterals name="NORMAL" value="3"/>
    <eLiterals name="HIGH" value="4"/>
    <eLiterals name="VERY_HIGH" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JobStatus" instanceTypeName="JobStatus">
    <eLiterals name="UNDEFINED" value="-1" literal="UNDEFINED"/>
    <eLiterals name="SUBMITTED" value="1" literal="SUBMITTED"/>
    <eLiterals name="QUEUED" value="2"/>
    <eLiterals name="WAITING" value="3"/>
    <eLiterals name="RUNNING" value="4"/>
    <eLiterals name="TERMINATED" value="5" literal="TERMINATED"/>
    <eLiterals name="CANCELLED" value="6" literal="CANCELLED"/>
    <eLiterals name="ALREADY_DOWNLOADED" value="7" literal="ALREADY_DOWNLOADED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgressOptions" instanceTypeName="ProgressOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobId" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Specifies the id of the job whose progression the user wants to see."/>
        <details key="shortOption" value="i"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobOwner" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Specifies the owner of the job."/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListProgression" instanceTypeName="ListProgression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbJobs" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Represents the number of jobs in progression list."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="progress" upperBound="-1"
        eType="#//Progression" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="Represents the list of jobs in progression"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Progression" instanceTypeName="Progression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobId" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job id."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobName" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job name."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wallTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job wall time."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Start date and time of the job (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="End date and time of the job (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percent" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Represent the job progression"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//JobStatus"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job status."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListQueues" instanceTypeName="ListQueues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbQueues" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Represents the number of queues."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queues" upperBound="-1"
        eType="#//Queue" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="Represents the list of queues."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Queue" instanceTypeName="Queue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the queue name."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxJobCpu" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the maximum number of Cups that a job can use."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxProcCpu" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the maximum number of Cpus of the queue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Represents the queue memory size."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wallTime" eType="ecore:EDataType Ecore.ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the total wallTime of the queue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="node" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the maximum number of nodes of the queue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbRunningJobs" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Is the total running jobs in the queue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbJobsInQueue" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Is the total number of jobs in the queue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//QueueStatus"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the status of the queue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="#//QueuePriority"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Represents the priority of the queue."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the queue description."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QueuePriority" instanceTypeName="QueuePriority">
    <eLiterals name="UNDEFINED" value="-1"/>
    <eLiterals name="VERY_LOW" value="1"/>
    <eLiterals name="LOW" value="2"/>
    <eLiterals name="NORMAL" value="3"/>
    <eLiterals name="HIGH" value="4"/>
    <eLiterals name="VERY_HIGH" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="QueueStatus" instanceTypeName="QueueStatus">
    <eLiterals name="NOT_STARTED" literal="NOT_STARTED"/>
    <eLiterals name="STARTED" value="1" literal="STARTED"/>
    <eLiterals name="RUNNING" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobResult" instanceTypeName="JobResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobId" eType="ecore:EDataType Ecore.ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Represents the id of the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the path to the job output results."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the path to the file containing errors occured during job's execution. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputDir" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the path to the file containing errors occured during job's execution. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListJobResults" instanceTypeName="ListJobResults">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbJobs" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Is the number of jobs."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Results" upperBound="-1"
        eType="#//JobResult" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="Represents the list of completed jobs results."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadCriterion" instanceTypeName="LoadCriterion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadType" eType="#//LoadType"
        defaultValueLiteral="1">
      <eAnnotations source="Description">
        <details key="content" value="The criterion to automatically submit a job (for now three criterions are used: minimum number of waiting jobs, minimum number of running jobs and the total number of jobs). This option is used only if the machine identifier is equal to autom (this keyword is used to submit automatically a job)"/>
        <details key="shortOption" value="L"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LoadType" instanceTypeName="LoadType">
    <eLiterals name="USE_NB_WAITING_JOBS" literal="USE_NB_WAITING_JOBS"/>
    <eLiterals name="USE_NB_JOBS" value="1" literal="USE_NB_JOBS"/>
    <eLiterals name="USE_NB_RUNNING_JOBS" value="2" literal="USE_NB_RUNNING_JOBS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Work" instanceTypeName="Work">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="Is the id of the session that contained the job submission command"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationId" eType="ecore:EDataType Ecore.ecore#//ELong"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Is the id of the machine on which the job has been submitted."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="Represents the name assigned to the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job priority. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="The current status of the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Represents the execution end date of the job (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="owner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job owner."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estimatedHour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Is the maximum wall-clock time during which the job can run (in seconds)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doneRatio" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Represents the job owner group name."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the textual description of the job."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="batchJobId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="Represents the batch job id (given by the underlying batch scheduler )."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateCreated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Date and time when job was submitted (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateEnded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Date and time when job was submitted (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateStarted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Date and time when job was submitted (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastUpdated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="Date and time when job was submitted (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="Is the id of the session that contained the job submission command"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="Is the id of the session that contained the job submission command"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="submitDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="Date and time when job was submitted (unix timestamp)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="Is the id of the session that contained the job submission command"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCPU" eType="ecore:EDataType Ecore.ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="The current status of the job."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
