<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UMS_Data_CLI"
    nsURI="http://www.sysfera.com/emf/ums/data/cli" nsPrefix="ums_data_cli">
  <eClassifiers xsi:type="ecore:EClass" name="AddUserOptions" instanceTypeName="AddUserOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the VISHNU user identifier"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the firstname of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the lastname of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="privilege" lowerBound="1"
        eType="ecore:EEnum UMS_Data.ecore#//PrivilegeType" defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="is the privilege of the user (admin or simple user)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the email of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateUserOptions" instanceTypeName="UpdateUserOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the VISHNU user identifier"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="shortOption" value="f"/>
        <details key="content" value="represents the updated firstname of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="shortOption" value="l"/>
        <details key="content" value="represents the updated lastname of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="privilege" eType="ecore:EEnum UMS_Data.ecore#//PrivilegeType"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="shortOption" value="p"/>
        <details key="content" value="represents the updated privilege of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="shortOption" value="m"/>
        <details key="content" value="represents the updated email adress of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddMachineOptions" instanceTypeName="AddMachineOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the name of the machine"/>
        <details key="shortOption" value="n"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="site" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the location of the machine"/>
        <details key="shortOption" value="s"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineDescription" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the description of the machine"/>
        <details key="shortOption" value="t"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the language in which the description of the machine has been done"/>
        <details key="shortOption" value="l"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddLocalAccountOptions" instanceTypeName="AddLocalAccountOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="The userId represents the VISHNU user identifier of the user of the local user configuration"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="The MachineId represents the identifier of the machine associated to the local user configuration"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acLogin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="accLogin represents the login of the user on the associated machine"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshKeyPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="sshKeyPath is the path of the ssh key of the user on the associated machine"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homeDirectory" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="HomeDirectory is the path of the home directory of the user on the associated machine"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
