<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UMS_Data"
    nsURI="http://www.sysfera.com/emf/ums/data" nsPrefix="ums_data">
  <eClassifiers xsi:type="ecore:EClass" name="ConnectOptions" instanceTypeName="ConnectOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closePolicy" eType="#//SessionCloseType"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="is an option for closing session automatically"/>
        <details key="shortOption" value="p"/>
        <details key="userOption" value="VISHNU_CLOSE_POLICY"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionInactivityDelay"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="The sessionInactivityDelay is the maximum delay in seconds between two API commands when the CLOSE_ON_TIMEOUT option is set"/>
        <details key="shortOption" value="d"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="substituteUserId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is an option which allows an admin to open a session as if he/she was a specific user identified by his/her userId"/>
        <details key="shortOption" value="s"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Session" instanceTypeName="Session">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the VISHNU session identifier of the session"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the VISHNU user identifier of the user who has opened the session"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the key of the session generated by VISHNU"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateLastConnect" eType="ecore:EDataType Ecore.ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="is the date of the last connection to the session (the UNIX timestamps is used)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateCreation" eType="ecore:EDataType Ecore.ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="is the date of the first connection to the session (the UNIX timestamps is used)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateClosure" eType="ecore:EDataType Ecore.ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="is the date of the closure of the session (the UNIX timestamps is used)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//StatusType"
        defaultValueLiteral="1">
      <eAnnotations source="Description">
        <details key="content" value="represents the status of the session"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closePolicy" eType="#//SessionCloseType"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="is the way to close the session"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="is the inactivity delay in seconds associated to the CLOSE_ON_TIMEOUT option"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListSessions" instanceTypeName="ListSessions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1"
        eType="#//Session" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="is the list of session objects"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListSessionOptions" instanceTypeName="ListSessionOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//StatusType"
        defaultValueLiteral="1">
      <eAnnotations source="Description">
        <details key="content" value="specifies the status of the sessions which will be listed"/>
        <details key="shortOption" value="t"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionClosePolicy" eType="#//SessionCloseType"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="specifies the closure mode of the sessions which will be listed (CLOSE_ON_TIMEOUT or CLOSE_ON_DISCONNECT)"/>
        <details key="shortOption" value="p"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionInactivityDelay"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="specifies the inactivity delay in seconds of the sessions which will be listed"/>
        <details key="shortOption" value="d"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="allows the user to list sessions opened on a specific machine"/>
        <details key="shortOption" value="m"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adminListOption" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="Description">
        <details key="content" value="is an admin option for listing all sessions of all users"/>
        <details key="shortOption" value="a"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is an admin option for listing sessions opened by a specific user"/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="allows the user to list all commands launched within a specific session"/>
        <details key="shortOption" value="i"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDateOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="allows the user to organize the commands listed by providing  the start date (the UNIX timestamp of the start date is used)"/>
        <details key="shortOption" value="s"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDateOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="allows the user to organize the commands listed by providing  the end date (the timestamp of the end date is used). By default, the end date is the current day"/>
        <details key="shortOption" value="e"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" instanceTypeName="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the VISHNU user identifier"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the password of the user. At the beginning, an admin can give a temporary password or it is automatically generated by the System. "/>
        <details key="shortOption" value="w"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the firstname of the user"/>
        <details key="shortOption" value="f"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the lastname of the user"/>
        <details key="shortOption" value="l"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="privilege" eType="#//PrivilegeType"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="is the privilege of the user (admin or simple user)"/>
        <details key="shortOption" value="p"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the email of the user"/>
        <details key="shortOption" value="m"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//StatusType"
        defaultValueLiteral="1">
      <eAnnotations source="Description">
        <details key="content" value="represents the status of the user"/>
        <details key="shortOption" value="s"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListUsers" instanceTypeName="ListUsers">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="is the list of users objects"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" instanceTypeName="Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the identifier of a command"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="The sessionId is the identifier of the session define in the database"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="The machineId is the identifier of the machine used by the command"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmdDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="cmdDescription is the description of the command"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmdStartTime" eType="ecore:EDataType Ecore.ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="cmdStartTime is the date of the command beginning (the UNIX timestamps is used)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmdEndTime" eType="ecore:EDataType Ecore.ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="cmdEndTime is the date of the command end (the UNIX timestamps is used)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListCommands" instanceTypeName="ListCommands">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Commands" upperBound="-1"
        eType="#//Command" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="is the list of commands objects"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListCmdOptions" instanceTypeName="ListCmdOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adminListOption" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="Description">
        <details key="content" value="is an admin option for listing all commands of all users"/>
        <details key="shortOption" value="a"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is an admin option for listing commands launched by a specific user identified by his/her userId"/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="lists all commands launched within a specific session"/>
        <details key="shortOption" value="i"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDateOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="allows the user to organize the commands listed by providing  the start date (the UNIX timestamp of the start date is used)"/>
        <details key="shortOption" value="s"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDateOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="allows the user to organize the commands listed by providing  the end date (the timestamp of the end date is used). By default, the end date is the current day"/>
        <details key="shortOption" value="e"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalAccount" instanceTypeName="LocalAccount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="The userId represents the VISHNU user identifier of the user of the local user configuration"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="The MachineId represents the identifier of the machine associated to the local user configuration"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acLogin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="accLogin represents the login of the user on the associated machine"/>
        <details key="shortOption" value="l"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshKeyPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="sshKeyPath is the path of the ssh key of the user on the associated machine"/>
        <details key="shortOption" value="s"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homeDirectory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="HomeDirectory is the path of the home directory of the user on the associated machine"/>
        <details key="shortOption" value="d"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListLocalAccounts" instanceTypeName="ListLocalAccounts">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts" upperBound="-1"
        eType="#//LocalAccount" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="is a list of LocalAccount objects which encapsulates local user configurations"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListLocalAccOptions" instanceTypeName="ListLocalAccOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adminListOption" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="Description">
        <details key="content" value="is an admin option for listing all local configurations of all users "/>
        <details key="shortOption" value="a"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is an admin option for listing the local configurations of a specific user "/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is an option for listing local user configurations on a specific machine"/>
        <details key="shortOption" value="i"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Machine" instanceTypeName="Machine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the identifier of the machine"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the name of the machine"/>
        <details key="shortOption" value="n"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="site" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the location of the machine"/>
        <details key="shortOption" value="s"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the description of the machine"/>
        <details key="shortOption" value="d"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the language in which the description of the machine has been done"/>
        <details key="shortOption" value="l"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//StatusType"
        defaultValueLiteral="1">
      <eAnnotations source="Description">
        <details key="content" value="represents the status of the machine"/>
        <details key="shortOption" value="t"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListMachines" instanceTypeName="ListMachines">
    <eStructuralFeatures xsi:type="ecore:EReference" name="machines" upperBound="-1"
        eType="#//Machine" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="is a list of machines objects which encapsulates the machines information"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListMachineOptions" instanceTypeName="ListMachineOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is an admin option for listing machines in which a specific user has a local configuration"/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listAllmachine" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="Description">
        <details key="content" value="is an option for listing all VISHNU machines"/>
        <details key="shortOption" value="a"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is an option for listing information about a specific machine"/>
        <details key="shortOption" value="m"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" instanceTypeName="Configuration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listConfUsers" upperBound="-1"
        eType="#//User" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="is the list of users objects"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listConfMachines" upperBound="-1"
        eType="#//Machine" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="is a list of machines objects"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listConfLocalAccounts"
        upperBound="-1" eType="#//LocalAccount" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="is the list of LocalAccount objects"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionValue" instanceTypeName="OptionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the name of an option"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the value of an option"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListOptionsValues" instanceTypeName="ListOptionsValues">
    <eStructuralFeatures xsi:type="ecore:EReference" name="optionValues" upperBound="-1"
        eType="#//OptionValue" containment="true">
      <eAnnotations source="Description">
        <details key="content" value="is a list of optionValue objects which encapsulates the optionValue information"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListOptOptions" instanceTypeName="ListOptOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listAllDeftValue" eType="ecore:EDataType Ecore.ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="Description">
        <details key="content" value="is an option for listing all default option values defined by VISHNU administrator"/>
        <details key="shortOption" value="a"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is an admin option for listing the options of a specific user"/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value=" allows the user to get the value of a specific option identified by its name  "/>
        <details key="shortOption" value="n"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SessionCloseType" instanceTypeName="SessionCloseType">
    <eAnnotations source="Description">
      <details key="content" value="The SessionCloseType is an option for closing session automatically"/>
    </eAnnotations>
    <eLiterals name="UNDEFINED" literal="UNDEFINED"/>
    <eLiterals name="CLOSE_ON_TIMEOUT" value="1" literal="CLOSE_ON_TIMEOUT"/>
    <eLiterals name="CLOSE_ON_DISCONNECT" value="2" literal="CLOSE_ON_DISCONNECT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrivilegeType" instanceTypeName="PrivilegeType">
    <eAnnotations source="Description">
      <details key="content" value="The PrivilegeType represents the privilege type of a user"/>
    </eAnnotations>
    <eLiterals name="USER" literal="USER"/>
    <eLiterals name="ADMIN" value="1" literal="ADMIN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatusType" instanceTypeName="StatusType">
    <eAnnotations source="Description">
      <details key="content" value="represents the different states of a VISHNU object"/>
    </eAnnotations>
    <eLiterals name="INACTIVE" literal="INACTIVE"/>
    <eLiterals name="ACTIVE" value="1" literal="ACTIVE"/>
  </eClassifiers>
</ecore:EPackage>
