<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UMS_Data_CLI"
    nsURI="http://www.sysfera.com/emf/ums/data/cli" nsPrefix="ums_data_cli">
  <eClassifiers xsi:type="ecore:EClass" name="AddUserOptions" instanceTypeName="AddUserOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the firstname of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the lastname of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="privilege" lowerBound="1"
        eType="ecore:EEnum UMS_Data.ecore#//PrivilegeType" defaultValueLiteral="-1">
      <eAnnotations source="Description">
        <details key="content" value="is the privilege of the user (admin or simple user)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="is the email of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateUserOptions" instanceTypeName="UpdateUserOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the VISHNU user identifier"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="shortOption" value="f"/>
        <details key="content" value="represents the updated firstname of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="shortOption" value="l"/>
        <details key="content" value="represents the updated lastname of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="privilege" eType="ecore:EEnum UMS_Data.ecore#//PrivilegeType"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="shortOption" value="p"/>
        <details key="content" value="represents the updated privilege of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="shortOption" value="m"/>
        <details key="content" value="represents the updated email address of the user"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EEnum UMS_Data.ecore#//StatusType"
        defaultValueLiteral="1">
      <eAnnotations source="Description">
        <details key="shortOption" value="s"/>
        <details key="content" value="represents the status of the user (LOCKED or ACTIVE)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddMachineOptions" instanceTypeName="AddMachineOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the name of the machine"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="site" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the location of the machine"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the language used for the description of the machine"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshPublicKeyFile" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="contains the path to the SSH public key used by VISHNU to access local user accounts"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineDescription" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the description of the machine"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateMachineOptions" instanceTypeName="UpdateMachineOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the identifier of the machine"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the name of the machine"/>
        <details key="shortOption" value="n"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="site" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the location of the machine"/>
        <details key="shortOption" value="s"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the description of the machine"/>
        <details key="shortOption" value="d"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="represents the language used for the description of the machine"/>
        <details key="shortOption" value="l"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EEnum UMS_Data.ecore#//StatusType"
        defaultValueLiteral="1">
      <eAnnotations source="Description">
        <details key="content" value="represents the status of the machine"/>
        <details key="shortOption" value="t"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshPublicKeyFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="contains the path to the SSH public key used by VISHNU to access local user accounts"/>
        <details key="shortOption" value="k"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddLocalAccountOptions" instanceTypeName="AddLocalAccountOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="The userId represents the VISHNU user identifier of the user of the local user configuration"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="machineId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="The MachineId represents the identifier of the machine associated to the local user configuration"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acLogin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="accLogin represents the login of the user on the associated machine"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshKeyPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="Description">
        <details key="content" value="sshKeyPath is the path of the ssh key of the user on the associated machine"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homeDirectory" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="HomeDirectory is the path of the home directory of the user on the associated machine"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddAuthSystemsOptions" instanceTypeName="AddAuthSystemsOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="corresponds to the user-authentication system's name"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the URI of the user-authentication systems (by the form host:port for LDAP)"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authLogin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the login used to connect to the user-authentication system"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authPassword" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the password used to connect to the user-authentication system"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userPasswordEncryption"
        lowerBound="1" eType="ecore:EEnum UMS_Data.ecore#//EncryptionMethod" defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="represents the encryption method used to encrypt user's password"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EEnum UMS_Data.ecore#//AuthentType"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="represents the type of the user-authentication systems"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ldapBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is an option for user-authentication system based on LDAP which specifies the DN of the root entry "/>
        <details key="shortOption" value="b"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateAuthSystemsOptions" instanceTypeName="UpdateAuthSystemsOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authSystemId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the identifier, generated by VISHNU, of the user-authentication system"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="corresponds to the user-authentication system's name"/>
        <details key="shortOption" value="n"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the URI of the user-authentication systems (by the form host:port for LDAP)"/>
        <details key="shortOption" value="i"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authLogin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the login used to connect to the user-authentication system"/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authPassword" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the password used to connect to the user-authentication system"/>
        <details key="shortOption" value="w"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userPasswordEncryption"
        eType="ecore:EEnum UMS_Data.ecore#//EncryptionMethod" defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="represents the encryption method used to encrypt user's password"/>
        <details key="shortOption" value="e"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum UMS_Data.ecore#//AuthentType"
        defaultValueLiteral="0">
      <eAnnotations source="Description">
        <details key="content" value="represents the type of the user-authentication system"/>
        <details key="shortOption" value="t"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ldapBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is an option for user-authentication system based on LDAP which specifies the DN of the root entry "/>
        <details key="shortOption" value="b"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuthentType" instanceTypeName="AuthentType">
    <eAnnotations source="Description">
      <details key="content" value="represents the type of the user-authentication systems"/>
    </eAnnotations>
    <eLiterals name="LDAP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateLocalAuthAccOptions" instanceTypeName="UpdateLocalAuthAccOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authSystemId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is the identifier of the user-authentication system"/>
        <details key="shortOption" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="represents the VISHNU user identifier"/>
        <details key="shortOption" value="u"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acLogin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;">
      <eAnnotations source="Description">
        <details key="content" value="is an option to change the login of the user on the associated user-authentication system"/>
        <details key="shortOption" value="l"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EncryptionMethod" instanceTypeName="EncryptionMethod">
    <eAnnotations source="Description">
      <details key="content" value="represents the name of the encryption method "/>
    </eAnnotations>
    <eLiterals name="SSHA"/>
  </eClassifiers>
</ecore:EPackage>
