'\" t
.\"     Title: addWork
.\"    Author:  SysFera SA <info@sysfera.com>
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: December 2012
.\"    Manual: TMS C++ API Reference
.\"    Source: VISHNU ZMQ_beta
.\"  Language: English
.\"
.TH "ADDWORK" "3" "December 2012" "VISHNU ZMQ_beta" "TMS C++ API Reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
addWork \- Allows to create a work consisting in running jobs\&.
.SH "SYNOPSIS"
.HP \w'int\ vishnu::addWork('u
.BI "int vishnu::addWork(const\ string&\ " "sessionKey" ", Work&\ " "work" ", const\ AddWorkOptions&\ " "option\ =\ AddWorkOptions()" ");"
.SH "DESCRIPTION"
.PP
This command adds a work in vishnu
.SH "ARGUMENTS"
.PP
\fIsessionKey\fR
.RS 4
Input argument\&. The session key\&.
.RE
.PP
\fIwork\fR
.RS 4
Output argument\&. The work to add\&.
.RE
.PP
\fIoption\fR
.RS 4
Input argument\&. Options to add the work\&.
.RE
.SH "EXCEPTIONS"
.PP
The following exceptions may be thrown:
.PP
"Vishnu not available (Service bus failure)" [1]
.RS 4
.RE
.PP
"Vishnu not available (Database error)" [2]
.RS 4
.RE
.PP
"Vishnu not available (Database connection)" [3]
.RS 4
.RE
.PP
"Vishnu not available (System)" [4]
.RS 4
.RE
.PP
"Vishnu not available (SSH error)" [9]
.RS 4
.RE
.PP
"Error invalid parameters" [10]
.RS 4
.RE
.PP
"The sessionKey is expired\&. The session is closed\&." [29]
.RS 4
.RE
.PP
"The machine id is unknown" [32]
.RS 4
.RE
.PP
"The batch scheduler type is unknown" [101]
.RS 4
.RE
.PP
"The batch scheduler indicates an error" [102]
.RS 4
.RE
.PP
"Permission denied" [104]
.RS 4
.RE
.SH "AUTHOR"
.PP
\fB SysFera SA\fR <\&info@sysfera.com\&>
.RS 4
Developed the first version of these man pages as part of the VISHNU project.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2012 SysFera SA
.br
.PP
These manual pages are provided under the following conditions:
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
.RE
.PP
This software is governed by the CECILL licence under French law and abiding by the rules of distribution of free software. You can use, modify and/ or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
.PP
As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty and the software's author, the holder of the economic rights, and the successive licensors have only limited liability.
.PP
In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software's suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
.sp
