GRANT SELECT ON vishnu.vishnu TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.users TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.machine TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.clmachine TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.optionu TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.state TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.cpu TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.description TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.vsession TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.account TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.optionvalue TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.threshold TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.command TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.filetransfer TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.filesub TO vishnu_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON vishnu.job TO vishnu_user;
