/**
 * \file ListUsersServer.hpp
 * \brief This file contains the VISHNU QueryServer class.
 * \author Daouda Traore (daouda.traore@sysfera.com) and 
 *   Eugène PAMBA CAPO-CHICHI (eugene.capochichi@sysfera.com)
 * \date February 2011 
 */
#ifndef _LIST_USERS_H_SERVER_
#define _LIST_USERS_H_SERVER_

#include <string>
#include <vector>
#include <list>
#include <iostream>
#include "boost/date_time/posix_time/posix_time.hpp"

#include "SessionServer.hpp"
#include "ListUsers.hpp"

/**
 * \class ListUsersServer 
 * \brief ListUsersServer class implementation 
 */
class ListUsersServer
{

public:
  
  /**
   * \fn ListUsersServer(const SessionServer& session)
   * \param session The object which encapsulates the session information (ex: identifier of the session)
   * \brief Constructor, raises an exception on error
   */
  explicit ListUsersServer(const SessionServer& session);
  /**
   * \fn ListUsersServer(const std::string& option,
   *                     const SessionServer& session)
   * \param option The ListUsersServer option 
   * \param session The object which encapsulates the session information (ex: identifier of the session)
   * \brief Constructor, raises an exception on error
   */
  ListUsersServer(const std::string& option, const SessionServer& session);

  /**
   * \brief Function to treat the ListUsersServer options 
   * \fn void processOptions(UserServer userServer,
   *                         const std::string& options,
   *                         std::string& sqlRequest)
   * \param userServer the object which encapsulates user information
   * \param options option 
   * \param sqlRequest the sql data base request
   * \return raises an exception on error
   */
  void processOptions(UserServer userServer, const std::string& options, std::string& sqlRequest);

 /**
  * \brief Function to list machines information 
  * \fn UMS_Data::ListUsers* list()
  * \return The pointer to the UMS_Data::ListUsers containing users information
  * \return raises an exception on error
  */
  UMS_Data::ListUsers* list();

  /**
   * \fn ~ListUsersServer()
   * \brief Destructor, raises an exception on error
   */
  ~ListUsersServer(); 

 private:

    /////////////////////////////////
  // Attributes
  /////////////////////////////////


 /**
  * \brief The ListUsersServer option 
  */
  std::string moption;
 /**
  * \brief The SessionServer object containing the encrypted identifier of the session
  *  generated by VISHNU
  */
  SessionServer msessionServer;
 /**
  * \brief The Object containing users information 
  */
  ListUsers* mlistUsers;
 /**
  * \brief An instance of vishnu database
  */
  Database *mdatabaseVishnu;


};

#endif
