/**
 * \file ListQueuesServer.hpp
 * \brief This file contains the VISHNU QueryServer class.
 * \author Daouda Traore (daouda.traore@sysfera.com) 
 * \date February 2011 
 */
#ifndef _LIST_QUEUES_H_SERVER_
#define _LIST_QUEUES_H_SERVER_

#include <string>

#include "SessionServer.hpp"
#include "ListQueues.hpp"

/**
 * \class ListQueuesServer 
 * \brief ListQueuesServer class implementation 
 */
class ListQueuesServer
{

public:
  
  /**
   * \fn ListQueuesServer(const SessionServer& session)
   * \param session The object which encapsulates the session information (ex: identifier of the session)
   * \brief Constructor, raises an exception on error
   */
  explicit ListQueuesServer(const SessionServer& session, const std::string& machineId, const BatchType& batchType, const std::string& option);
  /**
   * \fn ListQueuesServer(const std::string& option,
   *                     const SessionServer& session)
   * \param session The object which encapsulates the session information (ex: identifier of the session)
   * \brief Constructor, raises an exception on error
   */
  ListQueuesServer(const SessionServer& session);

 /**
  * \brief Function to list machines information 
  * \fn TMS_Data::ListQueues* list()
  * \return The pointer to the TMS_Data::ListQueues containing users information
  * \return raises an exception on error
  */
  TMS_Data::ListQueues* list();

  /**
   * \fn ~ListQueuesServer()
   * \brief Destructor, raises an exception on error
   */
  ~ListQueuesServer(); 

 private:

  /////////////////////////////////
  // Attributes
  /////////////////////////////////


  std::string moption;
 /**
  * \brief The SessionServer object containing the encrypted identifier of the session
  *  generated by VISHNU
  */
  SessionServer msessionServer;
  /**
   *\brief The id of the machine that the user wants to list queues
   */
  std::string mmachineId;
  /**
   *\brief The type of the bacth scheduler that the user wants to list queues
   */
  BatchType mbatchType;
  /**
  * \brief The Object containing users information 
  */
  TMS_Data::ListQueues* mlistQueues;
  /**
  * \brief The BatchServer instance 
  */
  BatchServer* mbatchServer;
};

#endif
