/**
 * \file AuthAccountProxy.hpp
 * \brief This file contains the VISHNU AuthAccountProxy class.
 * \author Daouda Traore (daouda.traore@sysfera.com)
 * \date February 2011
 */
#ifndef _AUTH_ACCOUNT_PROXY_H_
#define _AUTH_ACCOUNT_PROXY_H_

#include <string>
#include <iostream>

#include "SessionProxy.hpp"
#include "AuthAccount.hpp"

/**
 * \class AuthAccountProxy
 * \brief AuthAccountProxy class implementation
 */
class AuthAccountProxy
{

  public:

    /**
     * \param account The object which encapsulates the user authentification acccount information
     * \param session The object which encapsulates the session information (ex: identifier of the session)
     * \brief Constructor
     */
    AuthAccountProxy(const UMS_Data::AuthAccount& account, const SessionProxy& session);
    /**
     * \brief Function to add an user authentication account
     * \return raises an exception on error
     */
    int
    add();
    /**
     * \brief Function to update an user authentication account
     * \return raises an exception on error
     */
    int
    update();
    /**
     * \brief Function to removes an user authentication account (for a given user on a given authentication system) from VISHNU
     * \return raises an exception on error
     */
    int
    deleteAuthAccount();
    /**
     * \brief Function get SessionProxy object which contains the VISHNU session identifier
     * \return a SessionProy object which contains the VISHNU session information
     * \return raises an exception on error
     */
    SessionProxy
    getSessionProxy() const;
    /**
     * \brief Destructor, raises an exception on error
     */
    ~AuthAccountProxy();

  private:

    /**
     * \brief Function to combine add() and update() into one function
     * \param name The name of the service
     * \return raises an exception on error
     */
  int
  _addAuthAccountInformation(std::string name);

    /////////////////////////////////
    // Attributes
    /////////////////////////////////

    /**
     * \brief The object which encapsulates the user Acccount information
     */
    UMS_Data::AuthAccount mauthAccount;
    /**
     * \brief The SessionProxy object containing the encrypted identifier of the session
     *  generated by VISHNU
     */
    SessionProxy msessionProxy;
};
#endif
