/**
 * \file AuthSystemProxy.hpp
 * \brief This file contains the VISHNU AuthSystemProxy class.
 * \author Daouda Traore (daouda.traore@sysfera.com)
 * \date February 2011
 */
#ifndef _AUTH_SYSTEM_PROXY_H_
#define _AUTH_SYSTEM_PROXY_H_

#include <string>
#include <iostream>

#include "SessionProxy.hpp"
#include "AuthSystem.hpp"

/**
 * \class AuthSystemProxy
 * \brief AuthSystemProxy class implementation
 */
class AuthSystemProxy
{

  public:

    /**
     * \param system The object which encapsulates the authentification system
     * \param session The object which encapsulates the session information (ex: identifier of the session)
     * \brief Constructor
     */
    AuthSystemProxy(const UMS_Data::AuthSystem& system, const SessionProxy& session);
    /**
     * \brief Function to add an authentication system
     * \return raises an exception on error
     */
    int
    add();
    /**
     * \brief Function to update an authentication system
     * \return raises an exception on error
     */
    int
    update();
    /**
     * \brief Function to removes an authentication system
     * \return raises an exception on error
     */
    int
    deleteAuthSystem();
    /**
     * \brief Function get SessionProxy object which contains the VISHNU session identifier
     * \return a SessionProy object which contains the VISHNU session information
     * \return raises an exception on error
     */
    SessionProxy
    getSessionProxy() const;
    /**
     * \brief Function get AuthSystem information
     * \return the AuthSystem data structure
     */
    UMS_Data::AuthSystem
    getData() const;
    /**
     * \brief Destructor, raises an exception on error
     */
    ~AuthSystemProxy();

  private:

    /////////////////////////////////
    // Attributes
    /////////////////////////////////

    /**
     * \brief The object which encapsulates the user authentication system
     */
    UMS_Data::AuthSystem mauthSystem;
    /**
     * \brief The SessionProxy object containing the encrypted identifier of the session
     *  generated by VISHNU
     */
    SessionProxy msessionProxy;
};
#endif
