/**
 * \file ConfigurationProxy.hpp
 * \brief This file contains the VISHNU configurationProxy class.
 * \author Daouda Traore (daouda.traore@sysfera.com)
 * \date February 2011
 */
#ifndef _CONFIGURATION_PROXY_H_
#define _CONFIGURATION_PROXY_H_

#include <string>

#include "SessionProxy.hpp"
#include "Configuration.hpp"

/**
 * \class ConfigurationProxy
 * \brief ConfigurationProxy class implementation
 */
class ConfigurationProxy
{

  public:

    /**
     * \brief Constructor, raises an exception on error
     * \param filePath The file containing the configuration (serialized)
     * \param session The object which encapsulates the session information (ex: identifier of the session)
     */
    ConfigurationProxy(const std::string& filePath, const SessionProxy& session);
    /**
     * \brief Constructor, raises an exception on error
     * \param config The object which encapsulates the configuration description
     * \param session The object which encapsulates the session information (ex: identifier of the session)
     */
    ConfigurationProxy(UMS_Data::Configuration* config, const SessionProxy& session);
    /**
     * \brief Function to save the configuration of VISHNU
     * \return raises an exception on error
     */
    int save();
    /**
     * \brief Function to restore the configuration of VISHNU from a file
     * \return raises an exception on error
     */
    int restoreFromFile();
    /**
     * \brief Function to restore the configuration of VISHNU from an object (Data)
     * \return raises an exception on error
     */
    int restoreFromData();
    /**
     * \brief Function get the saved configuration of VISHNU
     * \return saved configuration
     * \return raises an exception on error
     */
    UMS_Data::Configuration* getData();
    /**
     * \brief Function get SessionProxy object which contains the VISHNU session identifier
     * \return a SessionProy object which contains the VISHNU session information
     * \return raises an exception on error
     */
    SessionProxy getSessionProxy();
    /**
     * \brief Destructor, raises an exception on error
     */
    ~ConfigurationProxy();

  private:
    /**
     * \brief Function to combine restoreFromFile() and restoreFromData() into one function
     * \param fromFile To select the call of restoreFromFile or restoreFromData function
     * \return raises an exception on error
     */
    int restore(bool fromFile=true);

    /////////////////////////////////
    // Attributes
    /////////////////////////////////

    /**
     * \brief A pointer on the Configuration object
     */
    UMS_Data::Configuration *mconfiguration;
    /**
     * \brief The SessionProxy object containing the encrypted identifier of the session
     *  generated by VISHNU
     */
    SessionProxy msessionProxy;
    /**
     * \brief the file containing the configuration (serialized)
     */
    std::string mfilePath;
};
#endif
