/**
 * \file LocalAccountProxy.hpp
 * \brief This file contains the VISHNU LocalAccountProxy class.
 * \author Daouda Traore (daouda.traore@sysfera.com)
 * \date February 2011
 */
#ifndef _LOCAL_ACCOUNT_PROXY_H_
#define _LOCAL_ACCOUNT_PROXY_H_

#include <string>

#include "SessionProxy.hpp"
#include "LocalAccount.hpp"

/**
 * \class LocalAccountProxy
 * \brief LocalAccountProxy class implementation
 */
class LocalAccountProxy
{

  public:

    /**
     * \brief Constructor, raises an exception on error
     * \param localAccount The object which encapsulates the user Acccount information
     * \param session The object which encapsulates the session information (ex: identifier of the session)
     */
    LocalAccountProxy(const UMS_Data::LocalAccount& localAccount, const SessionProxy& session);
    /**
     * \brief Function to add a new local user configuration
     * \return raises an exception on error
     */
    int add();
    /**
     * \brief Function to update a new local user configuration
     * \return raises an exception on error
     */
    int update();
    /**
     * \brief Function to removes a local user configuration (for a given user on a given machine) from VISHNU
     * \return raises an exception on error
     */
    int deleteLocalAccount();
    /**
     * \brief Function get SessionProxy object which contains the VISHNU session identifier
     * \return a SessionProy object which contains the VISHNU session information
     * \return raises an exception on error
     */
    SessionProxy getSessionProxy() const;
    /**
     * \brief Function get the VISHNU ssh public key
     * \return the VISHNU ssh public Key
     * \return raises an exception on error
     */
    std::string getSshPublicKey() const;
    /**
     * \brief Destructor, raises an exception on error
     */
    ~LocalAccountProxy();

  private:

    /**
     * \brief Function to combine add() and update() into one function
     * \param isNewLocalAccount to select the call of add or update function
     * \return raises an exception on error
     */
    int _addLocalAccountInformation(bool isNewLocalAccount=true);

    /////////////////////////////////
    // Attributes
    /////////////////////////////////

    /**
     * \brief The object which encapsulates the user Acccount information
     */
    UMS_Data::LocalAccount mlocalAccount;
    /**
     * \brief The SessionProxy object containing the encrypted identifier of the session
     *  generated by VISHNU
     */
    SessionProxy msessionProxy;
    /**
     * \brief The VISHNU ssh public Key
     */
    std::string  msshPublicKey;
};
#endif
