/**
 * \file MachineProxy.hpp
 * \brief This file contains the VISHNU MachineProxy class.
 * \author Daouda Traore (daouda.traore@sysfera.com)
 * \date February 2011
 */
#ifndef _MACHINE_PROXY_H_
#define _MACHINE_PROXY_H_

#include "SessionProxy.hpp"
#include "Machine.hpp"

/**
 * \class MachineProxy
 * \brief MachineProxy class implementation
 */
class MachineProxy
{

  public:

    /**
     * \brief Constructor, raises an exception on error
     * \param machine The object which encapsulates the information of the machine
     * \param session The object which encapsulates the session information (ex: identifier of the session)
     */
    MachineProxy(const UMS_Data::Machine& machine, const SessionProxy& session);
    /**
     * \brief Function to add a new machine
     * \return raises an exception on error
     */
    int add();
    /**
     * \brief Function to update machine description
     * \return raises an exception on error
     */
    int update();
    /**
     * \brief Function to remove a machine
     * \return raises an exception on error
     */
    int deleteMachine();
    /**
     * \brief Function get SessionProxy object which contains the VISHNU session identifier
     * \return a SessionProy object which contains the VISHNU session information
     * \return raises an exception on error
     */
    SessionProxy getSessionProxy();
    /**
     * \brief Function get machine information
     * \return Machine object encapsulates the information of the machine
     * \return raises an exception on error
     */
    UMS_Data::Machine getData();
    /**
     * \brief Destructor, raises an exception on error
     */
    ~MachineProxy();

  private:

    /////////////////////////////////
    // Attributes
    /////////////////////////////////

    /**
     * \brief The object which encapsulates the machine information
     */
    UMS_Data::Machine mmachine;
    /**
     * \brief The SessionProxy object containing the encrypted identifier of the session
     *  generated by VISHNU
     */
    SessionProxy msessionProxy;

};
#endif
