'\" t
.\"     Title: vishnu_submit_job
.\"    Author:  SysFera SA <info@sysfera.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: September 2012
.\"    Manual: TMS Command reference
.\"    Source: VISHNU 2.0
.\"  Language: English
.\"
.TH "VISHNU_SUBMIT_JOB" "1" "September 2012" "VISHNU 2.0" "TMS Command reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vishnu_submit_job \- Allows to submit a job consisting in running a given script on a machine\&.
.SH "SYNOPSIS"
.HP \w'\fBvishnu_submit_job\fR\ 'u
\fBvishnu_submit_job\fR [\fB\-h\fR] [\fB\-n\ \fR\fB\fIname\fR\fR] [\fB\-q\ \fR\fB\fIqueue\fR\fR] [\fB\-t\ \fR\fB\fIwallTime\fR\fR] [\fB\-m\ \fR\fB\fImemory\fR\fR] [\fB\-P\ \fR\fB\fInbCpu\fR\fR] [\fB\-N\ \fR\fB\fInbNodesAndCpuPerNode\fR\fR] [\fB\-o\ \fR\fB\fIoutputPath\fR\fR] [\fB\-e\ \fR\fB\fIerrorPath\fR\fR] [\fB\-M\ \fR\fB\fImailNotification\fR\fR] [\fB\-u\ \fR\fB\fImailNotifyUser\fR\fR] [\fB\-g\ \fR\fB\fIgroup\fR\fR] [\fB\-D\ \fR\fB\fIworkingDir\fR\fR] [\fB\-T\ \fR\fB\fIcpuTime\fR\fR] [\fB\-Q\fR] [\fB\-L\ \fR\fB\fIloadType\fR\fR] [\fB\-F\ \fR\fB\fIfileParams\fR\fR] [\fB\-V\ \fR\fB\fItextParams\fR\fR] [\fB\-w\ \fR\fB\fIworkId\fR\fR] \fImachineId\fR \fIscriptFilePath\fR
.SH "DESCRIPTION"
.PP
This command is used to submit a job to the specific batch scheduler associated to a machine\&. It allows describing a job in a script, using either the batch scheduler\*(Aqs directives or VISHNU\*(Aqs generic directives for all batch schedulers\&. If the machine identifier is equal to autom, the job will be automatically submitted on a best machine (for now three criterions are used: minimum number of waiting jobs, minimum number of running jobs and the total number of jobs) through the use of a script (scriptFilePath) which must be generic script using VISHNU\*(Aqs generic directives for all batch schedulers
.SH "OPTIONS"
.PP
\fB\-h \fR\fB\fIhelp\fR\fR
.RS 4
help about the command\&.
.RE
.PP
\fB\-n \fR\fB\fIname\fR\fR
.RS 4
Assigns a job name\&. The default is the path of job\&.
.RE
.PP
\fB\-q \fR\fB\fIqueue\fR\fR
.RS 4
Assigns the queue or class of the job\&.
.RE
.PP
\fB\-t \fR\fB\fIwallTime\fR\fR
.RS 4
The maximum wall\-clock time during which the job can run (in seconds)\&.
.RE
.PP
\fB\-m \fR\fB\fImemory\fR\fR
.RS 4
Is the memory size that the job requires (in MegaBytes)\&.
.RE
.PP
\fB\-P \fR\fB\fInbCpu\fR\fR
.RS 4
The number of cpu per node that the job requires\&.
.RE
.PP
\fB\-N \fR\fB\fInbNodesAndCpuPerNode\fR\fR
.RS 4
The number of nodes and processors per node (in the format nbNodes:nbCpuPerNode)\&. For example if you want to use 4 nodes with 3 cpus for each node, you must specify these numbers by "4:3"\&.
.RE
.PP
\fB\-o \fR\fB\fIoutputPath\fR\fR
.RS 4
Assigns the path and file for job output\&.
.RE
.PP
\fB\-e \fR\fB\fIerrorPath\fR\fR
.RS 4
Assigns the path and file for job error\&.
.RE
.PP
\fB\-M \fR\fB\fImailNotification\fR\fR
.RS 4
Assigns the notification type of the job\&. Valid type values are BEGIN, END, ERROR, and ALL (any state change)\&.
.RE
.PP
\fB\-u \fR\fB\fImailNotifyUser\fR\fR
.RS 4
The name of user to receive email notification of state changes as defined by the option mailNotification\&. The default value is the submitting user\&.
.RE
.PP
\fB\-g \fR\fB\fIgroup\fR\fR
.RS 4
Assigns a job group name\&.\&.
.RE
.PP
\fB\-D \fR\fB\fIworkingDir\fR\fR
.RS 4
Assigns a job remote working dir\&.
.RE
.PP
\fB\-T \fR\fB\fIcpuTime\fR\fR
.RS 4
Assigns a job cpu limit time (in seconds or in the format [[HH:]MM:]SS)\&.
.RE
.PP
\fB\-Q \fR\fB\fIselectQueueAutom\fR\fR
.RS 4
allows to select automatically a queue which has the number of nodes requested by the user\&.
.RE
.PP
\fB\-L \fR\fB\fIloadType\fR\fR
.RS 4
The criterion to automatically submit a job (for now three criterions are used: minimum number of waiting jobs, minimum number of running jobs and the total number of jobs)\&. This option is used only if the machine identifier is equal to autom (this keyword is used to submit automatically a job)\&. The value must be an integer\&. Predefined values are: 0 (USE_NB_WAITING_JOBS), 1 (USE_NB_JOBS), 2 (USE_NB_RUNNING_JOBS)\&.
.RE
.PP
\fB\-F \fR\fB\fIfileParams\fR\fR
.RS 4
Sets a list of local files as parameters for the script\&. These files will be uploaded onto the server before computing the script\&. At the execution time, each path can be accessed through an environment variable\&. E\&.g\&. \-\-fileParams "PFILE1=/path/to/file1 PFILE2=/path/to/file2" or \-F "PFILE1=/path/to/file1 PFILE2=/path/to/file2"\&. At the execution, the environment variable $PFILE1, for example, will point to the uploaded copy of the file /path/to/file1\&. The option \-\-fileParam or \-f allows to set each file individually\&. NOTE: The name of parameter as well as those of the corresponding environment are case\-insensitive\&. \&.
.RE
.PP
\fB\-V \fR\fB\fItextParams\fR\fR
.RS 4
Sets a list of parameters for the script so at the execution, each of parameter can be used as an environment variable\&. E\&.g\&. \-\-textParams "PARAM1=value1 PARAM2=value2" or \-F "PARAM1=value1 PARAM2=value2", will set the environment variables named PARAM1 and PARAM2 with value1 and value2, respectively\&. The option \-\-textParam or \-v allows to set each file individually\&. NOTE: The name of parameter as well as those of the corresponding environment are case\-insensitive\&.\&.
.RE
.PP
\fB\-w \fR\fB\fIworkId\fR\fR
.RS 4
Sets the identifier of the Work to which the job is related\&.
.RE
.SH "JOB OUTPUT ENVIRONMENT VARIABLES"
.PP
The VISHNU Job Manager set the following variables in the environment of the batch script\&.
.PP
\fBVISHNU_BATCHJOB_ID\fR
.RS 4
Set the identifier assigned to the job by the batch system\&.
.RE
.PP
\fBVISHNU_BATCHJOB_NAME\fR
.RS 4
Set the name of the job\&.
.RE
.PP
\fBVISHNU_SUBMIT_MACHINE_NAME\fR
.RS 4
Set the name of the machine on which the job has been submitted\&.
.RE
.PP
\fBVISHNU_BATCHJOB_NODEFILE\fR
.RS 4
Set the name of the file contain the list of nodes assigned to the job\&.
.RE
.PP
\fBVISHNU_BATCHJOB_NUM_NODES\fR
.RS 4
Set the total number of nodes in the job\*(Aqs resource allocation\&.
.RE
.PP
\fBVISHNU_OUTPUT_DIR\fR
.RS 4
Define a generic directory where files generated by scripts can be stored in order to be get out easily via the appropriate VISHNU commands (vishnu_get_output, vishnu_get_completed_jobs_output)\&. The directory is really set at the execution time with a directory automatically generated within the job\*(Aqs working directory\&.
.RE
.SH "ENVIRONMENT"
.PP
\fBVISHNU_CONFIG_FILE\fR
.RS 4
Contains the path to the local configuration file for VISHNU\&.
.RE
.SH "DIAGNOSTICS"
.PP
The following diagnostics may be issued on stderr and the command will return the code provided within brackets:
.PP
"Vishnu not available (Service bus failure)" [1]
.RS 4
.RE
.PP
"Vishnu not available (Database error)" [2]
.RS 4
.RE
.PP
"Vishnu not available (Database connection)" [3]
.RS 4
.RE
.PP
"Vishnu not available (System)" [4]
.RS 4
.RE
.PP
"Vishnu not available (SSH error)" [9]
.RS 4
.RE
.PP
"Error invalid parameters" [10]
.RS 4
.RE
.PP
"There is no open session in this terminal" [13]
.RS 4
.RE
.PP
"Missing parameters" [14]
.RS 4
.RE
.PP
"Vishnu initialization failed" [15]
.RS 4
.RE
.PP
"Undefined error" [16]
.RS 4
.RE
.PP
"The sessionKey is expired\&. The session is closed\&." [29]
.RS 4
.RE
.PP
"The machine id is unknown" [32]
.RS 4
.RE
.PP
"The batch scheduler type is unknown" [101]
.RS 4
.RE
.PP
"The batch scheduler indicates an error" [102]
.RS 4
.RE
.PP
"Permission denied" [104]
.RS 4
.RE
.PP
"The work id is unknown" [109]
.RS 4
.RE
.SH "EXAMPLE"
.PP
To submit on machine_1 the script toto:
.PP
vishnu_submit_job machine_1 toto
.PP
To submit automatically the script toto on the best machine (by the default the machine which has the minimum number of waiting jobs is selected):
.PP
vishnu_submit_job autom toto
.PP
To submit automatically the script toto on the best machine by using a machine which has the minimum total number of jobs:
.PP
vishnu_submit_job autom toto \-L 1
.SH "AUTHOR"
.PP
\fB SysFera SA\fR <\&info@sysfera.com\&>
.RS 4
Developed the first version of these man pages as part of the VISHNU project.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2012 SysFera SA
.br
.PP
These manual pages are provided under the following conditions:
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
.RE
.PP
This software is governed by the CECILL licence under French law and abiding by the rules of distribution of free software. You can use, modify and/ or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
.PP
As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty and the software's author, the holder of the economic rights, and the successive licensors have only limited liability.
.PP
In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software's suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
.sp
