#include <pbs_config.h>   /* the master config generated by configure */

#include <sys/types.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/wait.h>
#include <netinet/in.h>
#include <errno.h>
#include <fcntl.h>
#include <netdb.h>
#include <signal.h>
#include <termios.h>
#include <unistd.h>
#include <stdlib.h>
#include <assert.h>
#include <grp.h>
#include "csv.h"

#ifdef sun
#include <sys/stream.h>
#endif /* sun */

#if defined(HAVE_SYS_IOCTL_H)
#include <sys/ioctl.h>
#endif /* HAVE_SYS_IOCTL_H */

#if defined(HAVE_SYS_TTY_H)
#include <sys/tty.h>
#endif

#if defined(FD_SET_IN_SYS_SELECT_H)
#  include <sys/select.h>
#endif

#include "cmds.h"
#include "net_connect.h"
#include "log.h"
#include "port_forwarding.h"


#include <stdio.h>

#include "pbs_sub.h"

/* DefaultFilterPath is used to fall back on in order to maintain backwards compatibility.
   the new preferred path for the submit filter is ${libexecdir}/qsub_filter */

/* NOTE:  submitfilter specified using SUBMITFILTER in $TORQUEHOME/torque.cfg */

static char *DefaultFilterPath = "/usr/local/sbin/torque_submitfilter";

static char *DefaultXauthPath = XAUTH_PATH;

#define SUBMIT_FILTER_ADMIN_REJECT_CODE -1

#define MAX_QSUB_PREFIX_LEN 32

#define MAX_PROCS_DIGITS  15 /* A 15 digit number is a lot of processors. 100 trillion 
                                     will this be enough for the future? */

static char PBS_DPREFIX_DEFAULT[] = "#PBS";

char PBS_Filter[256];
char PBS_InitDir[256];
char PBS_RootDir[256];
char PBS_WorkDir[256];

char xauth_path[256];
char default_ckpt[256];

int validate_path = 1;
int rerunnable_by_default = 1;
int fault_tolerant_by_default = 0;
int x11child = 0;

int do_dir(char *);
int parse_file(int, char **, int);
int have_terminal = TRUE;

char *checkpoint_strings = "n,c,s,u,none,shutdown,periodic,enabled,interval,depth,dir";


/* globals */

int inter_sock = -1;

struct termios oldtio;

struct attrl *attrib = NULL;
char *new_jobname;                  /* return from submit request */
char dir_prefix[MAX_QSUB_PREFIX_LEN + 1];
char path_out[MAXPATHLEN + 1];
char destination[PBS_MAXDEST];
static char server_out[PBS_MAXSERVERNAME + PBS_MAXPORTNUM + 2];
char server_host[PBS_MAXHOSTNAME + 1];
char qsub_host[PBS_MAXHOSTNAME + 1];
char  owner_uid[MAXPATHLEN + 1];

long cnt2server_retry = -100;

/* state booleans for protecting already-set options */
int a_opt = FALSE;
int b_opt = FALSE;
int c_opt = FALSE;
int e_opt = FALSE;
int f_opt = FALSE;
int h_opt = FALSE;
int j_opt = FALSE;
int k_opt = FALSE;
int l_opt = FALSE;
int m_opt = FALSE;
int o_opt = FALSE;
int p_opt = FALSE;
int q_opt = FALSE;
int r_opt = FALSE;
int t_opt = FALSE;
int T_opt = FALSE;
int u_opt = FALSE;
int v_opt = FALSE;
int z_opt = FALSE;
int A_opt = FALSE;
int C_opt = FALSE;
int F_opt = FALSE;
int M_opt = FALSE;
int N_opt = FALSE;
int S_opt = FALSE;
int V_opt = FALSE;
int Depend_opt    = FALSE;
int Interact_opt  = FALSE;
int Run_Inter_opt = FALSE;
int Stagein_opt   = FALSE;
int Stageout_opt  = FALSE;
int Grouplist_opt = FALSE;
int Forwardx11_opt = FALSE;
int Umask_opt = FALSE;
char *v_value = NULL;

int parse_file(int    argc,  /* I */
               char **argv,  /* I */
               int    pass) {

}

#define TCONST_CFGFILE "torque.cfg"

#define PBS_SERVER_HOME "/var/spool/torque"
int load_config(

  char *config_buf, /* O */
  int   BufSize)    /* I */

  {

  return(0);
  }  /* END load_config() */


char *get_param(

  char *param,      /* I */
  char *config_buf) /* I */

  {
  char tmpLine[1024];

  char *param_val;
  char *new_val = NULL;

  /* FORMAT:  <PARAM> <WS> <VALUE> \n */

  /* NOTE:  does not support comments */

  /* if (strcasestr() == NULL) */

  /* NOTE: currently case-sensitive (FIXME) */

  if ((param_val = strstr(config_buf, param)) == NULL)
    {
    return(NULL);
    }

  strncpy(tmpLine, param_val, sizeof(tmpLine));

  strtok(tmpLine, " \t\n");

  if ((new_val = (char *)strtok(NULL, "\t \n")) == NULL)
    {
    return(NULL);
    }

  return(new_val);
  }  /* END get_param() */


int pbs_prepare_script(int    argc,  /* I */
                       char **argv,  /* I */
                       char **envp) {

  printf("*****%d*****%s****%s\n", argc, argv[0], argv[1]);
  int errflg;                         /* option error */
  static char script[MAXPATHLEN + 1] = ""; /* name of script file */
  char script_tmp[MAXPATHLEN + 1] = "";    /* name of script file copy */
  char *bnp;
  FILE *f;                            /* FILE pointer to the script */
  char *q_n_out;                      /* queue part of destination */
  char *s_n_out;                      /* server part of destination */
  /* server:port to send request to */
  int   connect;                      /* return from pbs_connect */
  char *errmsg;                       /* return from pbs_geterrmsg */

  struct stat statbuf;

  struct sigaction act;

  char config_buf[MAX_LINE_LEN];      /* Buffer holds config file */
  char *param_val;                    /* value of parameter returned from config */

  char *submit_args_str = NULL;       /* buffer to hold args */
  int   argi, argslen = 0;
  int   idx;
  int   have_intr_cmd = FALSE;
 
  if ((param_val = getenv("PBS_CLIENTRETRY")) != NULL)
  {
    cnt2server_retry = atoi(param_val);
  }

  /* set the submit_args */

  for (argi = 1;argi < argc;argi++)
  {
    argslen += strlen(argv[argi]) + 1;
  }

  if (argslen > 0)
  {
    submit_args_str = malloc(sizeof(char) * argslen);

    if (submit_args_str == NULL)
    {
      fprintf(stderr, "qsub: out of memory\n");

      exit(2);
    }

    *submit_args_str = '\0';

    for (argi = 1;argi < argc;argi++)
    {
      strcat(submit_args_str, argv[argi]);

      if (argi != argc - 1)
      {
        strcat(submit_args_str, " ");
      }
    }
  }

   /* check TORQUE config settings */

 //strncpy(PBS_Filter, getenv(getenv("SUBMIT_FILTER_PATH")), 255);

  /* check to see if PBS_Filter exists.  If not then fall back to the default hard-coded file */

  if (stat(PBS_Filter, &statbuf) == -1)
    {
    strncpy(PBS_Filter, DefaultFilterPath, 255);
    }

  strncpy(xauth_path, DefaultXauthPath, 255);

  strncpy(default_ckpt, CHECKPOINT_UNSPECIFIED, sizeof(default_ckpt));

  validate_path = 1;  /* boolean - by default verify '-d' working dir locally */

  server_host[0]  = '\0';
  qsub_host[0]    = '\0';
  owner_uid[0]    = '\0';

  /*if (getenv("PBSDEBUG") != NULL)
    {
    fprintf(stderr, "xauth_path=%s\n",
            xauth_path);
    }
*/
   //if (load_config(config_buf, sizeof(config_buf)) == 0)
    {
    /*if ((param_val = get_param("QSUBSLEEP", config_buf)) != NULL)
      {
      sleep(atoi(param_val));
      }

    if ((param_val = get_param("SUBMITFILTER", config_buf)) != NULL)
      {
      strncpy(PBS_Filter, param_val, sizeof(PBS_Filter));
      PBS_Filter[sizeof(PBS_Filter) - 1] = '\0';
      }

    if ((param_val = get_param("SERVERHOST", config_buf)) != NULL)
      {
      strncpy(server_host, param_val, sizeof(server_host));
      server_host[sizeof(server_host) - 1] = '\0';
      }

    if ((param_val = get_param("QSUBHOST", config_buf)) != NULL)
      {
      strncpy(qsub_host, param_val, sizeof(qsub_host));
      qsub_host[sizeof(qsub_host) - 1] = '\0';
      }*/

  }

  printf("*****%d*****%s****%s\n", argc, argv[0], argv[1]);
} 

