'\" t
.\"     Title: VISHNU_UMS.deleteMachine
.\"    Author:  SysFera SAS <info@sysfera.com>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: February 2011
.\"    Manual: Python API Reference
.\"    Source: VISHNU 1.0
.\"  Language: English
.\"
.TH "VISHNU_UMS\&.DELETEM" "3" "February 2011" "VISHNU 1.0" "Python API Reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
VISHNU_UMS.deleteMachine \- removes a machine from VISHNU
.SH "SYNOPSIS"
.HP \w'VISHNU_UMS\&.deleteMachine('u
.BI "VISHNU_UMS\&.deleteMachine(string\ " "sessionKey" ", string\ " "machineId" ");"
.SH "DESCRIPTION"
.PP
This command allows an admin to delete a machine from VISHNU\&. When a machine is deleted all of its information are deleted from VISHNU\&.
.SH "ARGUMENTS"
.PP
\fIsessionKey\fR
.RS 4
Input argument\&. The sessionKey is the encrypted identifier of the session generated by VISHNU\&.
.RE
.PP
\fImachineId\fR
.RS 4
Input argument\&. MachineId represents the identifier of the machine\&.
.RE
.SH "RETURNED OBJECTS"
.PP
\fIerrorCode (integer)\fR
.RS 4
Output parameter\&. Contains 0 on success and the error code on failure\&.
.RE
.SH "EXCEPTIONS"
.PP
The following exceptions may be thrown:
.PP
SystemException("Internal Error: SysDS service failure" [1])
.RS 4
.RE
.PP
SystemException("Internal Error: Database returned an error" [2])
.RS 4
.RE
.PP
SystemException("Internal Error: Database connection failure" [3])
.RS 4
.RE
.PP
SystemException("Internal Error: System call failure" [4])
.RS 4
.RE
.PP
SystemException("Internal Error: Undefined exception" [9])
.RS 4
.RE
.PP
UMSVishnuException("The user is not an administrator" [25])
.RS 4
.RE
.PP
UMSVishnuException("The session key is unrecognized" [28])
.RS 4
.RE
.PP
UMSVishnuException("The sessionKey is expired\&. The session is closed\&." [29])
.RS 4
.RE
.PP
UMSVishnuException("The machine id is unknown" [32])
.RS 4
.RE
.SH "AUTHOR"
.PP
\fB SysFera SAS\fR <\&info@sysfera.com\&>
.RS 4
Developed the first version of these man pages as part of the VISHNU project.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2011 SysFera SAS
.br
.PP
These manual pages are provided under the following conditions:
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
.RE
.PP
This software is governed by the CECILL licence under French law and abiding by the rules of distribution of free software. You can use, modify and/ or redistribute the software under the terms of the CeCILL license as circulated by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
.PP
As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the license, users are provided only with a limited warranty and the software's author, the holder of the economic rights, and the successive licensors have only limited liability.
.PP
In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or developing or reproducing the software by the user in light of its specific status of free software, that may mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the software's suitability as regards their requirements in conditions enabling the security of their systems and/or data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
.sp
