/**
 * \file ListQueuesServer.hpp
 * \brief This file contains the VISHNU QueryServer class.
 * \author Daouda Traore (daouda.traore@sysfera.com) 
 * \date February 2011 
 */
#ifndef _LIST_QUEUES_H_SERVER_
#define _LIST_QUEUES_H_SERVER_

#include <string>

#include "SessionServer.hpp"
#include "ListQueues.hpp"

/**
 * \class ListQueuesServer 
 * \brief ListQueuesServer class implementation 
 */
class ListQueuesServer
{

public:
  
  /**
   * \param session The object which encapsulates the session information (ex: identifier of the session)
   * \param machineId The machine identifier
   * \param batchType The batch scheduler Type
   * \param option The option value
   * \brief Constructor, raises an exception on error
   */
  explicit ListQueuesServer(const SessionServer& session, const std::string& machineId, const BatchType& batchType, const std::string& option);
  /**
   * \param session The object which encapsulates the session information (ex: identifier of the session)
   * \brief Constructor, raises an exception on error
   */
  ListQueuesServer(const SessionServer& session);

 /**
  * \brief Function to list machines information 
  * \return The pointer to the TMS_Data::ListQueues containing users information
  * \return raises an exception on error
  */
  TMS_Data::ListQueues* list();

  /**
   * \brief Destructor, raises an exception on error
   */
  ~ListQueuesServer(); 

 private:

  /////////////////////////////////
  // Attributes
  /////////////////////////////////

  /**
   * \brief The option value
   *  generated by VISHNU
   */
  std::string moption;
  /**
  * \brief The Object containing users information 
  */
  TMS_Data::ListQueues* mlistQueues;
  /**
  * \brief The BatchServer instance 
  */
  BatchServer* mbatchServer;
};

#endif
